### ISSUE TITLE
Electric Strike Lock for Testing

### ISSUE THREAD

**Issue by nelsonic** [dwyl/smart-home-security-system#15]
@th0mas I've sent you one of these:
https://www.ebay.co.uk/itm/HOMSECUR-500KG-Holding-Force-Electric-Strike-Lock-For-Wood-Door-Metal-Door/143172372012
![image](https://user-images.githubusercontent.com/194400/87450904-0fbf2300-c5f7-11ea-921a-92ceacf5292e.png)

Listing says Item location: `MIDDLESEX, United Kingdom` but I'm never sure if they are just going to ship it from Shenzhen ...
They have provided a Royal Mail tracking number: NU726704085GB (_which is a good sign_).

Tom, as you noted in #14 we still need to figure out how to power the lock. 
Would you mind doing a few minutes of research to figure out what kind of step-down transformer will be required to convert the 48V 600ma from the POE to 12V 3A for the lock? 

e.g. Could this work? https://www.ebay.co.uk/itm/Step-Down-Volt-Converter-Power-Supply-Adaptor-20V-550V-24V-36V-48V-to-12V-3A-uk/193433206182

![image](https://user-images.githubusercontent.com/194400/87511986-2f456280-c66e-11ea-93da-3bf13a30be8b.png)

**Comment by nelsonic** [comment]
This might be the way to go: **£8.99** seems reasonable during development. 💭 
https://smile.amazon.co.uk/JnDeeTM-Supply-ADAPTER-Transformer-Powering/dp/B0086D9J00
![12v3a-power-supply-amazon](https://user-images.githubusercontent.com/194400/87541922-01761300-c69a-11ea-9655-9e2fb0d28c17.png)

@th0mas please LMK if you agree so the order can be placed. 

<hr />

If we need to buy 10+ of these we might opt for a cheaper (_but still just as reliable_) version:
https://www.aliexpress.com/item/32950630087.html
![image](https://user-images.githubusercontent.com/194400/87545301-a0e9d480-c69f-11ea-968b-bc6de4c22320.png)

Though I'm definitely tempted to pay the extra 56p to have the ebay buyer protection in case it never arrives ... 🙄 
https://www.ebay.co.uk/itm/AC-DC-12V-3A-Power-Supply-Adapter-charger-Transformer-strip-light/183517311842
![image](https://user-images.githubusercontent.com/194400/87545697-4f8e1500-c6a0-11ea-8347-c3557b729d4a.png)

**Comment by nelsonic** [comment]
12v 3A Power Supply ordered for @th0mas along with other tools required to hook everything up.
![amazon-order-power-supply-for-tom](https://user-images.githubusercontent.com/194400/87580250-1de07280-c6cf-11ea-9b34-0fca86e5d4fb.png)

**Comment by t0mhaines** [comment]
Electronic strike lock connected and working, closing

**Comment by nelsonic** [comment]
@th0mas please document how you have got it working (_the circuit diagram_) when you can. thanks 👍
