### ISSUE TITLE
Hacking UART (What are the implications for us using PN532)?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/smart-home-security-system#16]
If we are going to be powering/communicating with our NFC/RFID Reader over **`UART`**,
we need to be _aware_ that if the `PN532` is **_accessible_ from _outside_ the building**,
our system is **insecure by _definition_**. 

Watch the first 14 mins of this DEF CON presentation:
[![image](https://user-images.githubusercontent.com/194400/87582534-6e0d0400-c6d2-11ea-8956-7f59cd92869b.png)](https://youtu.be/h5PRvBpLuJs)
https://youtu.be/h5PRvBpLuJs

In the immediate term the implication is: don't put the `PN532` outside.
We will need to mount it on the _inside_ of the building, with a custom 3D printed enclosure:

![image](https://user-images.githubusercontent.com/194400/87585701-613edf00-c6d7-11ea-8136-fb9677ec847d.png)

Obviously the people on the _inside_ of the building are welcome (_encouraged_) to try and (**White Hat**) hack the systems in the building if they have physical access to them. We will have a [bug bounty](https://en.wikipedia.org/wiki/Bug_bounty_program) for people who can demonstrate a _novel_ hack and along with write-up and a potential fix.

@th0mas in light of UARTs hack-ability, do you feel there are any other considerations/mitigations necessary for enhancing the security of the system? 💭

**Comment by t0mhaines** [comment]
First thing to note here: we're using UART as a communication method between our PN532 board and our Elixir Circuits UART-based library. 

**We are not running a `tty` connection over UART**

This means, that, similar to *any other protocol*, potential attackers could theoretically write arbitrary commands to our Raspberry Pi. Unlike the video you linked however, our UART port does not link to a tty shell where they can write arbitrary shell commands. They could write spoof PN532 messages, but this does not give them control of the device.

Spoofing PN532 messages **could** work, as you could send a card read message with a spoofed ID - but this isn't a UART specific problem - its an "external peripherals" problem.

To mitigate against this - 

+ We currently send heartbeat requests to PN532, if these get interrupted (e.g. someones unplugged our PN532), we could put the lock in a "failsafe" mode until its manually reset from the hub.

+ Solder on wires to headers, this makes "non-destructive" entry more difficult

I think the UART pins are connected to `ttyAMA0` on boot until our application initialises, so the Pi will be vulnerable for ~ 30 seconds on reboot. However, the Pi hasn't booted into a shell yet either so it may not acknowledge commands.

TL;DR: This is a peripheral problem, not a UART problem

**Comment by nelsonic** [comment]
@th0mas agreed, it's definitely a _general_ peripherals problem. 👍 
An attacker is far more likely to [**clone**](https://medium.com/insidersec0x42/how-i-finally-managed-to-clone-a-nfc-tag-4a9f64ef49c5) or **spoof** an NFC/RFID ID than attempt to physically compromise the RPI via the `UART` interface. Given that there is a heartbeat between the edge device/node and the hub and that the device

I think that the heartbeat coupled with logging will be enough to mitigate or at least intercept and deal with potentially malicious activity on the network. With the `2FA` for external doors we will have decent security. 

Closing. 👍
