### ISSUE TITLE
Add Additional Installation Instructions to README.md

### ISSUE THREAD

**Issue by nelsonic** [dwyl/smart-home-security-system#18]
The Scenic drivers:
https://github.com/dwyl/smart-home-firmware/blob/0be0578a77381f17a0edd17882c75b89ae4b33c7/mix.exs#L62
Require a few build dependencies to be installed. see:  https://github.com/boydm/scenic_driver_glfw#installing-on-macos

@th0mas do you remember installing these on your Mac?

**Comment by t0mhaines** [comment]
Wiring schema for readme:

![dwyl_bb](https://user-images.githubusercontent.com/9089056/88680487-7577d880-d0e8-11ea-86ab-4ca5288f3f77.png)

**Comment by t0mhaines** [comment]
Added in #19
