### ISSUE TITLE
Test NFC performance using SPI Library

### ISSUE THREAD

**Issue by t0mhaines** [dwyl/smart-home-security-system#6]
At some point I need to see if NFC performance is any better over SPI or if its a myth.

I'll do this by running the Adafruit PN532 python library and seeing how performance measures up.

**Comment by t0mhaines** [comment]
Tested on Raspbian using `libnfc 1.7.1`:

+ No performance gain - still can't read the fob type tags
+ SPI setup is a pain, uses 4 wires instead of 2 for UART
+ Seems to randomly fail?

Conclusion:

Simpler is possibly better, lets stick with UART it seems to work for our use case

**Comment by nelsonic** [comment]
@th0mas thanks for proactively testing this. Great that the result was in favour of simplicity (UART). 👍
